stages:
  - build
  - test

build_project:
  stage: build
  script:
    - gradle build
  tags:
    - java
    - gradle

test_project:
  stage: test
  script:
    - gradle test
  tags:
    - java
    - gradle