image: frekele/gradle:latest

stages:
  - build
  - test

build:
  stage: build
  script:
  - gradle assemble
  - gradle compileTestJava

test:
  stage: test
  only:
    - master
    - develop
  script:
  - gradle test
